version: '3.5'
services:
  influxdb:
    image: influxdb:1.8.3
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=YourPassword
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=YourPassword
    volumes:
      - ./data/influxdb-volume:/var/lib/influxdb
    ports:
      - "8086:8086"
    networks:
      - tig-docker
    labels:
      - "container_group=TIG-DOCKER"

  telegraf:
    #image: telegraf
    build: .
    command: -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
    container_name: telegraf
    restart: always
    environment:
       - HOSTNAME=telegraf
       - INFLUXDB_HOST="influxdb"
       - INFLUXDB_PORT=8086
       - DATABASE=telegraf
    volumes:
      - './config/telegraf-volume:/etc/telegraf:rw'
      - './config/telegraf-volume/telegraf.d:/etc/telegraf/telegraf.d:rw'
    links:
      - influxdb
    networks:
      - tig-docker
    labels:
      - "container_group=TIG-DOCKER"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    environment:
      - GF_DEFAULT_INSTANCE_NAME=grafana
      - GF_SERVER_ROOT_URL=https://host.cl
      - GF_SECURITY_ADMIN_PASSWORD=YourPassword
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,raintank-worldping-app,jdbranham-diagram-panel
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_SERVER_DOMAIN=https://host.cl
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_HOST=mysql-server.cl:3306
      - GF_DATABASE_NAME=db_name
      - GF_DATABASE_USER=db_user
      - GF_DATABASE_PASSWORD=db_password
    volumes:
      - ./data/grafana-volume:/var/lib/grafana
      - './config/grafana-volume:/etc/grafana:rw'
    networks:
      - tig-docker
    ports:
      - 3000:3000
    labels:
      - "container_group=TIG-DOCKER"

networks:
  tig-docker:
